version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: devjobs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devjobs
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local

networks:
  my_network:
    driver: bridge
